export const CHANGE_CATEGORY='CHANGE_CATEGORY'
export const GET_CATEGORIES_SUCCES='GET_CATEGORIES_SUCCES'
export const GET_PRODUCTS_SUCCESS='GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_BY_CATEGORY='GET_PRODUCTS_BY_CATEGORY'